[package]
name = "tiler"
version = "0.1.0"
authors = ["evomassiny <hanzohatory@gamil.com>"]

[dependencies]
netcdf = { git = "https://github.com/mhiley/rust-netcdf", branch = "master" }
image = "*"
regex = "0.2"
